apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-pod
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","delete"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-pod-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-pod-rb
subjects:
- kind: ServiceAccount
  name: delete-pod-sa
roleRef:
  kind: Role
  name: delete-pod
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: test-delete
spec:
  serviceAccountName: delete-pod-sa
  containers:
  - name: nginx
    image: nginx:latest